### create new user
Post  https://rntrackserver.vercel.app/signup
Content-Type: application/json

{
    "email":"arlo2@arlo.com",
    "password": "arlotheper"
}

### login in user
Post https://rntrackserver.vercel.app/signin
Content-Type: application/json

{
    "email":"arlo@arlo.com",
    "password": "arlotheper"
}

